spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/moodmate
    username: root
    password: root

jwt:
  secret: asdfasdfqwehjafsdjkasfdasdfasdfasdfasfdasdfasfdasdfasdfadsf
  expiration_time: 180