spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://choizeus-db.c9oqueg2ur6d.us-east-2.rds.amazonaws.com:3306/moodmateTest?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: root
    password: wodnwodn0212

jwt:
  secret: asdfasdfqwehjafsdjkasfdasdfasdfasdfasfdasdfasfdasdfasdfadsf
  expiration_time: 180